# As of 2024-08-28
N100 = [
    "AAPL",
    "ABNB",
    "ADBE",
    "ADI",
    "ADP",
    "ADSK",
    "AEP",
    "AMAT",
    "AMD",
    "AMGN",
    "AMZN",
    "ANSS",
    "ARM",
    "ASML",
    "AVGO",
    "AZN",
    "BIIB",
    "BKNG",
    "BKR",
    "CCEP",
    "CDNS",
    "CDW",
    "CEG",
    "CHTR",
    "CMCSA",
    "COST",
    "CPRT",
    "CRWD",
    "CSCO",
    "CSGP",
    "CSX",
    "CTAS",
    "CTSH",
    "DASH",
    "DDOG",
    "DLTR",
    "DXCM",
    "EA",
    "EXC",
    "FANG",
    "FAST",
    "FTNT",
    "GEHC",
    "GFS",
    "GILD",
    "GOOG",
    "GOOGL",
    "HON",
    "IDXX",
    "ILMN",
    "INTC",
    "INTU",
    "ISRG",
    "KDP",
    "KHC",
    "KLAC",
    "LIN",
    "LRCX",
    "LULU",
    "MAR",
    "MCHP",
    "MDB",
    "MDLZ",
    "MELI",
    "META",
    "MNST",
    "MRNA",
    "MRVL",
    "MSFT",
    "MU",
    "NFLX",
    "NVDA",
    "NXPI",
    "ODFL",
    "ON",
    "ORLY",
    "PANW",
    "PAYX",
    "PCAR",
    "PDD",
    "PEP",
    "PYPL",
    "QCOM",
    "REGN",
    "ROP",
    "ROST",
    "SBUX",
    "SMCI",
    "SNPS",
    "TEAM",
    "TMUS",
    "TSLA",
    "TTD",
    "TTWO",
    "TXN",
    "VRSK",
    "VRTX",
    "WBD",
    "WDAY",
    "XEL",
    "ZS"
]

CEOS = [
    ("AAPL", "Timothy Cook"),
    ("MSFT", "Satya Nadella"),
    ("NVDA", "Jen-Hsun Huang"),
    ("GOOGL", "Sundar Pichai"),
    ("AMZN", "Andrew Jassy"),
    ("META", "Mark Zuckerberg"),
    ("AVGO", "Hock Tan"),
    ("TSLA", "Elon Musk"),
    ("COST", "Ron Vachris"),
    ("ASML", "Christophe Fouquet"),
    ("NFLX", "Theodore Sarandos"),
    ("AZN", "Pascal Soriot"),
    ("ADBE", "Shantanu Narayen"),
    ("AMD", "Lisa Su"),
    ("PEP", "Ramon Laguarta"),
    ("TMUS", "Michael Sievert"),
    ("LIN", "Sanjiv Lamba"),
    ("PDD", "Jiazhen Zhao"),
    ("CSCO", "Charles Robbins"),
    ("QCOM", "Cristiano Amon"),
    ("INTU", "Sasan Goodarzi"),
    ("TXN", "Haviv Ilan"),
    ("AMGN", "Robert Bradway"),
    ("AMAT", "Gary Dickerson"),
    ("ISRG", "Gary Guthart"),
    ("CMCSA", "Brian Roberts"),
    ("ARM", "Rene Haas"),
    ("REGN", "Leonard Schleifer"),
    ("HON", "Vimal Kapur"),
    ("VRTX", "Reshma Kewalramani"),
    ("BKNG", "Glenn Fogel"),
    ("MU", "Sanjay Mehrotra"),
    ("LRCX", "Timothy Archer"),
    ("ADI", "Vincent Roche"),
    ("KLAC", "Richard Wallace"),
    ("PANW", "Nikesh Arora"),
    ("ADP", "Maria Black"),
    ("SBUX", "Laxman Narasimhan"),
    ("MELI", "Marcos Galperín"),
    ("MDLZ", "Dirk Put"),
    ("GILD", "Daniel O'Day"),
    ("INTC", "Patrick Gelsinger"),
    ("SNPS", "Sassine Ghazi"),
    ("CDNS", "Anirudh Devgan"),
    ("CTAS", "Todd Schneider"),
    ("ABNB", "Brian Chesky"),
    ("PYPL", "James Chriss"),
    ("ORLY", "Brad Beckham"),
    ("NXPI", "Kurt Sievers"),
    ("CSX", "Joseph Hinrichs"),
    ("CRWD", "George Kurtz"),
    ("MAR", "Anthony Capuano"),
    ("WDAY", "Carl Eschenbach"),
    ("MRVL", "Matthew Murphy"),
    ("CEG", "Joseph Dominguez"),
    ("ROP", "Laurence Hunn"),
    ("FTNT", "Ken Xie"),
    ("ADSK", "Andrew Anagnost"),
    ("DASH", "Tony Xu"),
    ("AEP", "William Fehrman"),
    ("CHTR", "Christopher Winfrey"),
    ("TTD", "Jeffrey Green"),
    ("PCAR", "Preston Feight"),
    ("CPRT", "Jeffrey Liaw"),
    ("ROST", "Barbara Rentler"),
    ("KDP", "Timothy Cofer"),
    ("MNST", "Rodney Sacks"),
    ("PAYX", "John Gibson"),
    ("MCHP", "Ganesh Moorthy"),
    ("ODFL", "Kevin Freeman"),
    ("KHC", "Carlos Abrams-Rivera"),
    ("IDXX", "Jonathan Mazelsky"),
    ("TEAM", "Michael Cannon-Brookes"),
    ("EA", "Andrew Wilson"),
    ("DDOG", "Olivier Pomel"),
    ("FAST", "Daniel Florness"),
    ("GEHC", "Peter Arduini"),
    ("VRSK", "Lee Shavel"),
    ("EXC", "Calvin Butler"),
    ("CTSH", "Ravi Singisetti"),
    ("SMCI", "Charles Liang"),
    ("CCEP", "Damian Gammell"),
    ("BKR", "Lorenzo Simonelli"),
    ("FANG", "Travis Stice"),
    ("XEL", "Robert Frenzel"),
    ("MRNA", "Stephane Bancel"),
    ("ON", "Hassane El-Khoury"),
    ("LULU", "Calvin McDonald"),
    ("CSGP", "Andrew Florance"),
    ("DXCM", "Kevin Sayer"),
    ("CDW", "Christine Leahy"),
    ("BIIB", "Christopher Viehbacher"),
    ("ZS", "Jagtar Chaudhry"),
    ("ANSS", "Ajei Gopal"),
    ("TTWO", "Strauss Zelnick"),
    ("GFS", "Thomas Caulfield"),
    ("DLTR", "Richard Dreiling"),
    ("ILMN", "Jacob Thaysen"),
    ("WBD", "David Zaslav"),
    ("MDB", "Dev Ittycheria"),
    ("GOOG", "Sundar Pichai")
]
